package application;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

public class CreateReminder1Controller {

	// Event Listener on Button.onAction
	@FXML
	public void NextToDeco(ActionEvent event) {
		// TODO Autogenerated
	}
}
